### ISSUE TITLE
Cleanup base.html 

### ISSUE THREAD

**Issue by sinergatis** [aristippe/pathagar#43]
While I tend not to get involved too much in the templates, I checked `base.html` during the latest round of changes and I'm wondering if a cleanup would be in order, as it is arguably the most important template and some things are looking a bit convoluted:
- The navbar is wrapped on a `{% if user.is_authenticated %}` block, but performs the same check in some items.
- RSS seems to be only available to superuser?
- I _believe_ the original Pathagar pointed to different feeds from the RSS link, depending on the URL the user was visiting (so `/by-author` would contain a link to `/by-author.atom, etc), while currently it always points to the root feed.
- The upload link next to the search book does not take into account `allow_public_add_book`.
- Some variables are not always available and it's quite cumbersome to pass them around (related to the previous one, and to the next steps after #41 is closed)

I'm wondering if we could go through it and agree on what is should look like, and then proceed with a cleanup? Most of the issues seem to be a combination of original issues + django migration + new views + other changes, and I'd love to at least have this template as nice as possible. Note I'm not really talking about the looks, it's more like "_what do we want to be there_" and internal structure!

**Comment by sinergatis** [comment]
Also:
- `{% block script %}` seems to have been deleted at some point, but some templates still use it. We might take the chance to reintroduce it and revise some other blocks (CSS, title, etc).

**Comment by aristippe** [comment]
Indeed the base template could be improved. :) I forgot about the use of script and re-added it in commit 92d242525bb47f020bdad50f6e6838e92fde0a61. For other issues:

> The navbar is wrapped on a {% if user.is_authenticated %} block, but performs the same check in some items.

The outer block is there since base is now included in the login page, the header and footer is hidden. The inner block was for add book and now it's if authenticated or allow_public_add_book. Perhaps once the authentication changes are done, we can decide if authentication is required for the site, either that alone or some optional additional user class might be required for uploads.

> RSS seems to be only available to superuser?

That was a temporary setting while RSS was broken. Thanks to your fix, fixed.

> I believe the original Pathagar pointed to different feeds from the RSS link, depending on the URL the user was visiting …

Yes though I'm not sure if that's the best method. calibre's OPDS feed, as well as possibly others or many, place them all together in some menu. That's might be the ideal way though some OPDS overhaul.

> Some variables are not always available and it's quite cumbersome to pass them around

Maybe you're referring to book count in the footer? I had realized that was broken and hadn't gotten around to fixing it yet. I'm not sure if I prefer to have that or not in the footer. It was originally in a stats box, though I forgot if it was included only in list view. I'm undecided if book count should be included in the footer, though additional links like for tag list, a possible about page, contact, etc, are probably well placed there.

**Comment by sinergatis** [comment]
Closed at #45!
